language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
    # Script to generate the issue in github used for comments
  - npm run create-issues -- $BASIC_AUTH_HEADER false
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: docs/
  fqdn: www.statox.fr
