#!/usr/bin/env bash

CLEAR_DIR='src/secrets'
SECRET_DIR='src/.secrets'

# Check if their are some files in the clear directory
if [ -n "$(ls -A $CLEAR_DIR 2>/dev/null)" ]
then
  echo "Secrets repository seems already decrypted."
  exit 0
fi

mkdir -p "$CLEAR_DIR"
encfs "${PWD}/$SECRET_DIR" "${PWD}/$CLEAR_DIR"


if [ $? -ne 0 ]; then
    RED='\033[0;31m'
    NC='\033[0m'
    echo -e "${RED}Failed to decrypt secret path, continuing anyway${NC}"
fi
