name: deploy
on:
  # Trigger on push on master branch
  push:
    branches: [master]
  # Trigger manually
  workflow_dispatch:
  # Trigger on "todo-comment.yml" completion
  # CAUTION  it is triggered no matter the sucess state of the previous workflow
  workflow_run:
    workflows: ['Add todo entries']
    types:
      - completed
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: 🔀 Checkout
        uses: actions/checkout@v2
      - name: 🚩 Configure node
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: 🔧 Install, check and build
        run: |
          npm ci
          npm run prettier
          npm run build
      - name: 💬 Create issues for comments
        run: npm run create-issues -- ${{ secrets.TRAVIS_ACCESS_TOKEN }} false
      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          token: ${{ secrets.TRAVIS_ACCESS_TOKEN }}
