name: Add song chords

on:
  issue_comment:
    types:
      - created

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: 🔀 Checkout
        uses: actions/checkout@v2
      - name: 🚩 Configure node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: 🔧 Install and build
        run: npm ci
      - name: 💬 Read comment
        uses: ./.github/actions/add-song-chords-action
