name: Add todo entries

on:
  issue_comment:
    types:
      - created

jobs:
  issue_commented:
    # This job only runs for comments on the issue #145
    # when the comment comes from me
    # The id can be found with
    # curl -i https://api.github.com/repos/statox/blog/issues/[ISSUE_NR]
    name: Issue comment
    if: |
      github.event.sender.login == 'statox' &&
      github.event.issue.id == 1306520145
    runs-on: ubuntu-latest
    steps:
      - name: 🔀 Checkout
        uses: actions/checkout@v2
      - name: 🚩 Configure node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: 🔧 Install and build
        run: npm ci
      - name: 💬 Read comment
        uses: ./.github/actions/add-todo-entry-action
        with:
          issueId: ${{ github.event.issue.id }}
          login: ${{ github.event.sender.login }}
          commenterId: ${{ github.event.sender.id }}
          comment: ${{ github.event.comment.body }}
